version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-nfl
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiYTc3MTY3ZGQxNGNmNWViNjE2NWM2YzQzNzA1YzA1ZWMiLCJ0IjoiNjBkZjY4MDQtMmU0Yi00NDYzLWFhZjMtOWNiNmExYTNlOTRhIiwicyI6Ik9HRTJPV0kzTm1JdFlXSm1NaTAwWXprNUxUa3dOV1l0Tm1NNVpEZG1NbUptTUdNNSJ9
    networks:
      - tunnel-net

networks:
  tunnel-net:
    driver: bridge 


    