-- CreateTable
CREATE TABLE "Post" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Post_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Game" (
    "id" TEXT NOT NULL,
    "season" INTEGER NOT NULL,
    "week" INTEGER NOT NULL,
    "gameType" TEXT NOT NULL,
    "homeTeam" TEXT NOT NULL,
    "awayTeam" TEXT NOT NULL,
    "homeScore" INTEGER NOT NULL,
    "awayScore" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Game_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Play" (
    "id" TEXT NOT NULL,
    "gameId" TEXT,
    "oldGameId" TEXT,
    "homeTeam" TEXT,
    "awayTeam" TEXT,
    "seasonType" TEXT,
    "week" INTEGER,
    "posteam" TEXT,
    "posteamType" TEXT,
    "defteam" TEXT,
    "sideOfField" TEXT,
    "yardline100" DOUBLE PRECISION,
    "gameDate" TIMESTAMP(3),
    "quarterSecondsRemaining" INTEGER,
    "halfSecondsRemaining" INTEGER,
    "gameSecondsRemaining" INTEGER,
    "gameHalf" TEXT,
    "quarterEnd" INTEGER,
    "drive" DOUBLE PRECISION,
    "sp" INTEGER,
    "qtr" INTEGER,
    "down" DOUBLE PRECISION,
    "goalToGo" INTEGER,
    "time" TEXT,
    "yrdln" TEXT,
    "ydstogo" INTEGER,
    "ydsnet" DOUBLE PRECISION,
    "desc" TEXT,
    "playType" TEXT,
    "yardsGained" DOUBLE PRECISION,
    "shotgun" INTEGER,
    "noHuddle" INTEGER,
    "qbDropback" BOOLEAN,
    "qbKneel" INTEGER,
    "qbSpike" INTEGER,
    "qbScramble" INTEGER,
    "passLength" TEXT,
    "passLocation" TEXT,
    "airYards" DOUBLE PRECISION,
    "yardsAfterCatch" DOUBLE PRECISION,
    "runLocation" TEXT,
    "runGap" TEXT,
    "fieldGoalResult" TEXT,
    "kickDistance" DOUBLE PRECISION,
    "extraPointResult" TEXT,
    "twoPointConvResult" TEXT,
    "homeTimeoutsRemaining" TEXT,
    "awayTimeoutsRemaining" TEXT,
    "timeout" TEXT,
    "timeoutTeam" TEXT,
    "tdTeam" TEXT,
    "tdPlayerName" TEXT,
    "tdPlayerId" TEXT,
    "posteamTimeoutsRemaining" TEXT,
    "defteamTimeoutsRemaining" TEXT,
    "totalHomeScore" INTEGER,
    "totalAwayScore" INTEGER,
    "posteamScore" TEXT,
    "defteamScore" TEXT,
    "scoreDifferential" DOUBLE PRECISION,
    "posteamScorePost" TEXT,
    "defteamScorePost" TEXT,
    "scoreDifferentialPost" DOUBLE PRECISION,
    "noScoreProb" DOUBLE PRECISION,
    "oppFgProb" DOUBLE PRECISION,
    "oppSafetyProb" DOUBLE PRECISION,
    "oppTdProb" DOUBLE PRECISION,
    "fgProb" DOUBLE PRECISION,
    "safetyProb" DOUBLE PRECISION,
    "tdProb" DOUBLE PRECISION,
    "extraPointProb" DOUBLE PRECISION,
    "twoPointConversionProb" DOUBLE PRECISION,
    "ep" DOUBLE PRECISION,
    "epa" DOUBLE PRECISION,
    "totalHomeEpa" DOUBLE PRECISION,
    "totalAwayEpa" DOUBLE PRECISION,
    "totalHomeRushEpa" DOUBLE PRECISION,
    "totalAwayRushEpa" DOUBLE PRECISION,
    "totalHomePassEpa" DOUBLE PRECISION,
    "totalAwayPassEpa" DOUBLE PRECISION,
    "airEpa" DOUBLE PRECISION,
    "yacEpa" DOUBLE PRECISION,
    "compAirEpa" DOUBLE PRECISION,
    "compYacEpa" DOUBLE PRECISION,
    "totalHomeCompAirEpa" DOUBLE PRECISION,
    "totalAwayCompAirEpa" DOUBLE PRECISION,
    "totalHomeCompYacEpa" DOUBLE PRECISION,
    "totalAwayCompYacEpa" DOUBLE PRECISION,
    "totalHomeRawAirEpa" DOUBLE PRECISION,
    "totalAwayRawAirEpa" DOUBLE PRECISION,
    "totalHomeRawYacEpa" DOUBLE PRECISION,
    "totalAwayRawYacEpa" DOUBLE PRECISION,
    "wp" DOUBLE PRECISION,
    "defWp" DOUBLE PRECISION,
    "homeWp" DOUBLE PRECISION,
    "awayWp" DOUBLE PRECISION,
    "wpa" DOUBLE PRECISION,
    "vegasWpa" DOUBLE PRECISION,
    "vegasHomeWpa" DOUBLE PRECISION,
    "homeWpPost" DOUBLE PRECISION,
    "awayWpPost" DOUBLE PRECISION,
    "vegasWp" DOUBLE PRECISION,
    "vegasHomeWp" DOUBLE PRECISION,
    "totalHomeRushWpa" DOUBLE PRECISION,
    "totalAwayRushWpa" DOUBLE PRECISION,
    "totalHomePassWpa" DOUBLE PRECISION,
    "totalAwayPassWpa" DOUBLE PRECISION,
    "airWpa" DOUBLE PRECISION,
    "yacWpa" DOUBLE PRECISION,
    "compAirWpa" DOUBLE PRECISION,
    "compYacWpa" DOUBLE PRECISION,
    "totalHomeCompAirWpa" DOUBLE PRECISION,
    "totalAwayCompAirWpa" DOUBLE PRECISION,
    "totalHomeCompYacWpa" DOUBLE PRECISION,
    "totalAwayCompYacWpa" DOUBLE PRECISION,
    "totalHomeRawAirWpa" DOUBLE PRECISION,
    "totalAwayRawAirWpa" DOUBLE PRECISION,
    "totalHomeRawYacWpa" DOUBLE PRECISION,
    "totalAwayRawYacWpa" DOUBLE PRECISION,
    "puntBlocked" BOOLEAN,
    "firstDownRush" BOOLEAN,
    "firstDownPass" BOOLEAN,
    "firstDownPenalty" BOOLEAN,
    "thirdDownConverted" BOOLEAN,
    "thirdDownFailed" BOOLEAN,
    "fourthDownConverted" BOOLEAN,
    "fourthDownFailed" BOOLEAN,
    "incompletePass" BOOLEAN,
    "touchback" INTEGER,
    "interception" BOOLEAN,
    "puntInsideTwenty" TEXT,
    "puntInEndzone" BOOLEAN,
    "puntOutOfBounds" BOOLEAN,
    "puntDowned" BOOLEAN,
    "puntFairCatch" BOOLEAN,
    "kickoffInsideTwenty" TEXT,
    "kickoffInEndzone" BOOLEAN,
    "kickoffOutOfBounds" BOOLEAN,
    "kickoffDowned" BOOLEAN,
    "kickoffFairCatch" BOOLEAN,
    "fumbleForced" BOOLEAN,
    "fumbleNotForced" BOOLEAN,
    "fumbleOutOfBounds" BOOLEAN,
    "soloTackle" BOOLEAN,
    "safety" BOOLEAN,
    "penalty" BOOLEAN,
    "tackledForLoss" BOOLEAN,
    "fumbleLost" BOOLEAN,
    "ownKickoffRecovery" BOOLEAN,
    "ownKickoffRecoveryTd" BOOLEAN,
    "qbHit" BOOLEAN,
    "rushAttempt" BOOLEAN,
    "passAttempt" BOOLEAN,
    "sack" BOOLEAN,
    "touchdown" BOOLEAN,
    "passTouchdown" BOOLEAN,
    "rushTouchdown" BOOLEAN,
    "returnTouchdown" BOOLEAN,
    "extraPointAttempt" BOOLEAN,
    "twoPointAttempt" BOOLEAN,
    "fieldGoalAttempt" BOOLEAN,
    "kickoffAttempt" BOOLEAN,
    "puntAttempt" BOOLEAN,
    "fumble" BOOLEAN,
    "completePass" BOOLEAN,
    "assistTackle" BOOLEAN,
    "lateralReception" BOOLEAN,
    "lateralRush" BOOLEAN,
    "lateralReturn" BOOLEAN,
    "lateralRecovery" BOOLEAN,
    "passerPlayerId" TEXT,
    "passerPlayerName" TEXT,
    "passingYards" DOUBLE PRECISION,
    "receiverPlayerId" TEXT,
    "receiverPlayerName" TEXT,
    "receivingYards" DOUBLE PRECISION,
    "rusherPlayerId" TEXT,
    "rusherPlayerName" TEXT,
    "rushingYards" DOUBLE PRECISION,
    "lateralReceiverPlayerId" TEXT,
    "lateralReceiverPlayerName" TEXT,
    "lateralReceivingYards" DOUBLE PRECISION,
    "lateralRusherPlayerId" TEXT,
    "lateralRusherPlayerName" TEXT,
    "lateralRushingYards" DOUBLE PRECISION,
    "lateralSackPlayerId" TEXT,
    "lateralSackPlayerName" TEXT,
    "interceptionPlayerId" TEXT,
    "interceptionPlayerName" TEXT,
    "lateralInterceptionPlayerId" TEXT,
    "lateralInterceptionPlayerName" TEXT,
    "puntReturnerPlayerId" TEXT,
    "puntReturnerPlayerName" TEXT,
    "lateralPuntReturnerPlayerId" TEXT,
    "lateralPuntReturnerPlayerName" TEXT,
    "kickoffReturnerPlayerName" TEXT,
    "kickoffReturnerPlayerId" TEXT,
    "lateralKickoffReturnerPlayerId" TEXT,
    "lateralKickoffReturnerPlayerName" TEXT,
    "punterPlayerId" TEXT,
    "punterPlayerName" TEXT,
    "kickerPlayerName" TEXT,
    "kickerPlayerId" TEXT,
    "ownKickoffRecoveryPlayerId" TEXT,
    "ownKickoffRecoveryPlayerName" TEXT,
    "blockedPlayerId" TEXT,
    "blockedPlayerName" TEXT,
    "tackleForLoss1PlayerId" TEXT,
    "tackleForLoss1PlayerName" TEXT,
    "tackleForLoss2PlayerId" TEXT,
    "tackleForLoss2PlayerName" TEXT,
    "qbHit1PlayerId" TEXT,
    "qbHit1PlayerName" TEXT,
    "qbHit2PlayerId" TEXT,
    "qbHit2PlayerName" TEXT,
    "forcedFumblePlayer1Team" TEXT,
    "forcedFumblePlayer1PlayerId" TEXT,
    "forcedFumblePlayer1PlayerName" TEXT,
    "forcedFumblePlayer2Team" TEXT,
    "forcedFumblePlayer2PlayerId" TEXT,
    "forcedFumblePlayer2PlayerName" TEXT,
    "soloTackle1Team" TEXT,
    "soloTackle2Team" TEXT,
    "soloTackle1PlayerId" TEXT,
    "soloTackle2PlayerId" TEXT,
    "soloTackle1PlayerName" TEXT,
    "soloTackle2PlayerName" TEXT,
    "assistTackle1PlayerId" TEXT,
    "assistTackle1PlayerName" TEXT,
    "assistTackle1Team" TEXT,
    "assistTackle2PlayerId" TEXT,
    "assistTackle2PlayerName" TEXT,
    "assistTackle2Team" TEXT,
    "assistTackle3PlayerId" TEXT,
    "assistTackle3PlayerName" TEXT,
    "assistTackle3Team" TEXT,
    "assistTackle4PlayerId" TEXT,
    "assistTackle4PlayerName" TEXT,
    "assistTackle4Team" TEXT,
    "tackleWithAssist" BOOLEAN,
    "tackleWithAssist1PlayerId" TEXT,
    "tackleWithAssist1PlayerName" TEXT,
    "tackleWithAssist1Team" TEXT,
    "tackleWithAssist2PlayerId" TEXT,
    "tackleWithAssist2PlayerName" TEXT,
    "tackleWithAssist2Team" TEXT,
    "passDefense1PlayerId" TEXT,
    "passDefense1PlayerName" TEXT,
    "passDefense2PlayerId" TEXT,
    "passDefense2PlayerName" TEXT,
    "fumbled1Team" TEXT,
    "fumbled1PlayerId" TEXT,
    "fumbled1PlayerName" TEXT,
    "fumbled2PlayerId" TEXT,
    "fumbled2PlayerName" TEXT,
    "fumbled2Team" TEXT,
    "fumbleRecovery1Team" TEXT,
    "fumbleRecovery1Yards" DOUBLE PRECISION,
    "fumbleRecovery1PlayerId" TEXT,
    "fumbleRecovery1PlayerName" TEXT,
    "fumbleRecovery2Team" TEXT,
    "fumbleRecovery2Yards" DOUBLE PRECISION,
    "fumbleRecovery2PlayerId" TEXT,
    "fumbleRecovery2PlayerName" TEXT,
    "sackPlayerId" TEXT,
    "sackPlayerName" TEXT,
    "halfSack1PlayerId" TEXT,
    "halfSack1PlayerName" TEXT,
    "halfSack2PlayerId" TEXT,
    "halfSack2PlayerName" TEXT,
    "returnTeam" TEXT,
    "returnYards" DOUBLE PRECISION,
    "penaltyTeam" TEXT,
    "penaltyPlayerId" TEXT,
    "penaltyPlayerName" TEXT,
    "penaltyYards" DOUBLE PRECISION,
    "replayOrChallenge" INTEGER,
    "replayOrChallengeResult" TEXT,
    "penaltyType" TEXT,
    "defensiveTwoPointAttempt" BOOLEAN,
    "defensiveTwoPointConv" BOOLEAN,
    "defensiveExtraPointAttempt" BOOLEAN,
    "defensiveExtraPointConv" BOOLEAN,
    "safetyPlayerName" TEXT,
    "safetyPlayerId" TEXT,
    "season" INTEGER,
    "cp" DOUBLE PRECISION,
    "cpoe" DOUBLE PRECISION,
    "series" INTEGER,
    "seriesSuccess" INTEGER,
    "seriesResult" TEXT,
    "orderSequence" INTEGER,
    "startTime" TEXT,
    "timeOfDay" TEXT,
    "stadium" TEXT,
    "weather" TEXT,
    "nflApiId" TEXT,
    "playClock" INTEGER,
    "playDeleted" INTEGER,
    "playTypeNfl" TEXT,
    "specialTeamsPlay" TEXT,
    "stPlayType" DOUBLE PRECISION,
    "endClockTime" TEXT,
    "endYardLine" DOUBLE PRECISION,
    "fixedDrive" INTEGER,
    "fixedDriveResult" TEXT,
    "driveRealStartTime" TEXT,
    "drivePlayCount" DOUBLE PRECISION,
    "driveTimeOfPossession" TEXT,
    "driveFirstDowns" DOUBLE PRECISION,
    "driveInside20" TEXT,
    "driveEndedWithScore" BOOLEAN,
    "driveQuarterStart" DOUBLE PRECISION,
    "driveQuarterEnd" DOUBLE PRECISION,
    "driveYardsPenalized" DOUBLE PRECISION,
    "driveStartTransition" TEXT,
    "driveEndTransition" TEXT,
    "driveGameClockStart" TEXT,
    "driveGameClockEnd" TEXT,
    "driveStartYardLine" TEXT,
    "driveEndYardLine" TEXT,
    "drivePlayIdStarted" TEXT,
    "drivePlayIdEnded" TEXT,
    "awayScore" INTEGER,
    "homeScore" INTEGER,
    "location" TEXT,
    "result" INTEGER,
    "total" INTEGER,
    "spreadLine" DOUBLE PRECISION,
    "totalLine" DOUBLE PRECISION,
    "divGame" INTEGER,
    "roof" TEXT,
    "surface" DOUBLE PRECISION,
    "temp" DOUBLE PRECISION,
    "wind" DOUBLE PRECISION,
    "homeCoach" TEXT,
    "awayCoach" TEXT,
    "stadiumId" TEXT,
    "gameStadium" TEXT,
    "abortedPlay" INTEGER,
    "success" BOOLEAN,
    "passer" TEXT,
    "passerJerseyNumber" DOUBLE PRECISION,
    "rusher" TEXT,
    "rusherJerseyNumber" DOUBLE PRECISION,
    "receiver" TEXT,
    "receiverJerseyNumber" DOUBLE PRECISION,
    "pass" INTEGER,
    "rush" INTEGER,
    "firstDown" BOOLEAN,
    "special" INTEGER,
    "play" INTEGER,
    "passerId" TEXT,
    "rusherId" TEXT,
    "receiverId" TEXT,
    "name" TEXT,
    "jerseyNumber" DOUBLE PRECISION,
    "fantasyPlayerName" TEXT,
    "fantasyPlayerId" TEXT,
    "fantasy" TEXT,
    "fantasyId" TEXT,
    "outOfBounds" INTEGER,
    "homeOpeningKickoff" INTEGER,
    "qbEpa" DOUBLE PRECISION,
    "xyacEpa" DOUBLE PRECISION,
    "xyacMeanYardage" DOUBLE PRECISION,
    "xyacMedianYardage" DOUBLE PRECISION,
    "xyacSuccess" DOUBLE PRECISION,
    "xyacFd" DOUBLE PRECISION,
    "xpass" DOUBLE PRECISION,
    "passOe" DOUBLE PRECISION,

    CONSTRAINT "Play_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PlayerWeeklyStats" (
    "id" TEXT NOT NULL,
    "season" INTEGER NOT NULL,
    "week" INTEGER NOT NULL,
    "seasonType" TEXT NOT NULL,
    "playerId" TEXT NOT NULL,
    "playerName" TEXT NOT NULL,
    "position" TEXT NOT NULL,
    "team" TEXT NOT NULL,
    "opponent" TEXT NOT NULL,
    "fantasyPoints" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "fantasyPointsPPR" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "completions" INTEGER NOT NULL DEFAULT 0,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "passingYards" INTEGER NOT NULL DEFAULT 0,
    "passingTouchdowns" INTEGER NOT NULL DEFAULT 0,
    "interceptions" INTEGER NOT NULL DEFAULT 0,
    "sacks" INTEGER NOT NULL DEFAULT 0,
    "sackYards" INTEGER NOT NULL DEFAULT 0,
    "sackFumbles" INTEGER NOT NULL DEFAULT 0,
    "sackFumblesLost" INTEGER NOT NULL DEFAULT 0,
    "passingAirYards" INTEGER NOT NULL DEFAULT 0,
    "passingYardsAfterCatch" INTEGER NOT NULL DEFAULT 0,
    "passingFirstDowns" INTEGER NOT NULL DEFAULT 0,
    "passingEPA" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "passing2PtConversions" INTEGER NOT NULL DEFAULT 0,
    "carries" INTEGER NOT NULL DEFAULT 0,
    "rushingYards" INTEGER NOT NULL DEFAULT 0,
    "rushingTouchdowns" INTEGER NOT NULL DEFAULT 0,
    "rushingFumbles" INTEGER NOT NULL DEFAULT 0,
    "rushingFumblesLost" INTEGER NOT NULL DEFAULT 0,
    "rushingFirstDowns" INTEGER NOT NULL DEFAULT 0,
    "rushingEPA" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "rushing2PtConversions" INTEGER NOT NULL DEFAULT 0,
    "receptions" INTEGER NOT NULL DEFAULT 0,
    "targets" INTEGER NOT NULL DEFAULT 0,
    "receivingYards" INTEGER NOT NULL DEFAULT 0,
    "receivingTouchdowns" INTEGER NOT NULL DEFAULT 0,
    "receivingFumbles" INTEGER NOT NULL DEFAULT 0,
    "receivingFumblesLost" INTEGER NOT NULL DEFAULT 0,
    "receivingAirYards" INTEGER NOT NULL DEFAULT 0,
    "receivingYardsAfterCatch" INTEGER NOT NULL DEFAULT 0,
    "receivingFirstDowns" INTEGER NOT NULL DEFAULT 0,
    "receivingEPA" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "receiving2PtConversions" INTEGER NOT NULL DEFAULT 0,
    "racr" DOUBLE PRECISION,
    "targetShare" DOUBLE PRECISION,
    "airYardsShare" DOUBLE PRECISION,
    "wopr" DOUBLE PRECISION,
    "pacr" DOUBLE PRECISION,
    "dakota" DOUBLE PRECISION,
    "specialTeamsTouchdowns" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "PlayerWeeklyStats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Player" (
    "id" TEXT NOT NULL,
    "gsisId" TEXT NOT NULL,
    "displayName" TEXT,
    "commonFirstName" TEXT,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "shortName" TEXT,
    "footballName" TEXT,
    "suffix" TEXT,
    "esbId" TEXT,
    "nflId" TEXT,
    "pfrId" TEXT,
    "pffId" TEXT,
    "otcId" TEXT,
    "espnId" TEXT,
    "smartId" TEXT,
    "birthDate" TIMESTAMP(3),
    "positionGroup" TEXT,
    "position" TEXT,
    "ngsPositionGroup" TEXT,
    "ngsPosition" TEXT,
    "height" TEXT,
    "weight" INTEGER,
    "headshot" TEXT,
    "collegeName" TEXT,
    "collegeConference" TEXT,
    "jerseyNumber" TEXT,
    "rookieSeason" INTEGER,
    "lastSeason" INTEGER,
    "latestTeam" TEXT,
    "status" TEXT,
    "ngsStatus" TEXT,
    "ngsStatusDescription" TEXT,
    "yearsOfExperience" INTEGER,
    "pffPosition" TEXT,
    "pffStatus" TEXT,
    "draftYear" INTEGER,
    "draftRound" INTEGER,
    "draftPick" INTEGER,
    "draftTeam" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Player_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Post_name_idx" ON "Post"("name");

-- CreateIndex
CREATE INDEX "Game_season_week_idx" ON "Game"("season", "week");

-- CreateIndex
CREATE INDEX "Game_homeTeam_idx" ON "Game"("homeTeam");

-- CreateIndex
CREATE INDEX "Game_awayTeam_idx" ON "Game"("awayTeam");

-- CreateIndex
CREATE INDEX "Play_gameId_idx" ON "Play"("gameId");

-- CreateIndex
CREATE INDEX "Play_playType_idx" ON "Play"("playType");

-- CreateIndex
CREATE INDEX "Play_posteam_idx" ON "Play"("posteam");

-- CreateIndex
CREATE INDEX "Play_defteam_idx" ON "Play"("defteam");

-- CreateIndex
CREATE INDEX "Play_passerId_idx" ON "Play"("passerId");

-- CreateIndex
CREATE INDEX "Play_receiverId_idx" ON "Play"("receiverId");

-- CreateIndex
CREATE INDEX "Play_rusherId_idx" ON "Play"("rusherId");

-- CreateIndex
CREATE INDEX "PlayerWeeklyStats_playerId_idx" ON "PlayerWeeklyStats"("playerId");

-- CreateIndex
CREATE INDEX "PlayerWeeklyStats_playerName_idx" ON "PlayerWeeklyStats"("playerName");

-- CreateIndex
CREATE INDEX "PlayerWeeklyStats_season_idx" ON "PlayerWeeklyStats"("season");

-- CreateIndex
CREATE INDEX "PlayerWeeklyStats_team_idx" ON "PlayerWeeklyStats"("team");

-- CreateIndex
CREATE UNIQUE INDEX "PlayerWeeklyStats_playerId_season_week_seasonType_key" ON "PlayerWeeklyStats"("playerId", "season", "week", "seasonType");

-- CreateIndex
CREATE UNIQUE INDEX "Player_gsisId_key" ON "Player"("gsisId");

-- CreateIndex
CREATE INDEX "Player_position_idx" ON "Player"("position");

-- CreateIndex
CREATE INDEX "Player_latestTeam_idx" ON "Player"("latestTeam");

-- CreateIndex
CREATE INDEX "Player_displayName_idx" ON "Player"("displayName");

-- CreateIndex
CREATE INDEX "Player_gsisId_idx" ON "Player"("gsisId");

-- CreateIndex
CREATE INDEX "Player_pfrId_idx" ON "Player"("pfrId");

-- CreateIndex
CREATE INDEX "Player_pffId_idx" ON "Player"("pffId");

-- CreateIndex
CREATE INDEX "Player_nflId_idx" ON "Player"("nflId");
