version: '3.8'

services:
  nfl-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - nfl_cache:/app/cache
    environment:
      - R_ENVIRON_USER=/app/.Renviron
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1800M
        reservations:
          memory: 1000M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nfl-network

volumes:
  nfl_cache:

networks:
  nfl-network:
    driver: bridge 